name: Carbon CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        crystal_version: [latest]
        include:
          - os: ubuntu-latest
            crystal_version: 1.4.0
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Install dependencies
        run: shards install --skip-postinstall --skip-executables
      - name: Create .env file
        run: touch .env
      - name: Run tests
        run: crystal spec
